[phases.install]
cmds = [
  "pnpm install --frozen-lockfile",
  "cd server && pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "node_modules/.bin/vite build",
  "cd server && node_modules/.bin/prisma generate --schema ../prisma/schema.prisma",
  "cd server && node_modules/.bin/tsc"
]
